services:
  backend:
    image: ghcr.io/horoshovse/balancer-backend:latest
    ports:
      - "8081:80"
      - "443:443"
      - "443:443/udp" # for QUIC/HTTP3
      - "8080:8080" # API & UI port
      - "53:53/udp" # DNS UDP
      - "53:53/tcp" # DNS TCP
    volumes:
      - ./backend/certs:/app/certs
      - ./backend/data:/app/data
    environment:
      - DB_DSN=postgres://balancer:balancer@db:5432/balancer?sslmode=disable
      - DEV_MODE=false
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: balancer
      POSTGRES_PASSWORD: balancer
      POSTGRES_DB: balancer
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "54432:5432"
    restart: unless-stopped

  frontend:
    image: ghcr.io/horoshovse/balancer-frontend:latest
    ports:
      - "3000:80"
    restart: unless-stopped

volumes:
  postgres_data:
